import type {
  Schema,
  ValidationResult,
  ValidationError,
} from "../schema/types";
import type { SchemaBuilder } from "../schema/builders";

/**
 * WASM module interface
 * Auto-generated by wasm-pack
 */
export interface WasmModule {
  WasmValidator: {
    validate(schema_json: string, value_json: string): string;
    validate_at_path(
      schema_json: string,
      value_json: string,
      path_json: string,
    ): string;
  };
}

/**
 * Lazy-loaded WASM module singleton
 */
let wasmModule: WasmModule | null = null;

/**
 * Initialize WASM module
 * Must be called before validation
 */
export async function initWasm(): Promise<void> {
  if (wasmModule) return;

  try {
    // Dynamic import of WASM module
    const module = (await import("../../pkg/rustica.js")) as any;

    // For web target, call init function. For nodejs target, it's already loaded
    if (typeof module.default === "function") {
      await module.default();
    }

    wasmModule = module;
  } catch (error) {
    throw new Error(
      `Failed to load WASM module. Make sure to run 'npm run build:wasm' first. Error: ${error}`,
    );
  }
}

/**
 * Get initialized WASM module
 */
function getWasm(): WasmModule {
  if (!wasmModule) {
    throw new Error(
      "WASM module not initialized. Call initWasm() before validation.",
    );
  }
  return wasmModule;
}

/**
 * Core validator using WASM
 */
export class Validator {
  /**
   * Validate data against a schema
   *
   * @param schema - Schema definition (builder or JSON)
   * @param value - Data to validate
   * @returns Validation result with errors if any
   */
  static validate<T>(
    schema: SchemaBuilder<T> | Schema,
    value: unknown,
  ): ValidationResult {
    const wasm = getWasm();

    // Serialize schema to JSON
    const schemaJson = JSON.stringify(
      schema instanceof Object && "toJSON" in schema ? schema.toJSON() : schema,
    );

    // Serialize value to JSON
    const valueJson = JSON.stringify(value);

    // Call WASM validator (single call, zero-copy)
    const resultJson = wasm.WasmValidator.validate(schemaJson, valueJson);

    // Parse result
    return JSON.parse(resultJson) as ValidationResult;
  }

  /**
   * Validate data at a specific path in the schema
   * Useful for field-level validation in forms
   *
   * @param schema - Schema definition
   * @param value - Complete data object
   * @param path - Path to validate (e.g., ['user', 'email'])
   * @returns Validation result for the specific field
   */
  static validateAtPath<T>(
    schema: SchemaBuilder<T> | Schema,
    value: unknown,
    path: string[],
  ): ValidationResult {
    const wasm = getWasm();

    // Serialize inputs
    const schemaJson = JSON.stringify(
      schema instanceof Object && "toJSON" in schema ? schema.toJSON() : schema,
    );
    const valueJson = JSON.stringify(value);
    const pathJson = JSON.stringify(path);

    // Call WASM validator (single call)
    const resultJson = wasm.WasmValidator.validate_at_path(
      schemaJson,
      valueJson,
      pathJson,
    );

    // Parse result
    return JSON.parse(resultJson) as ValidationResult;
  }

  /**
   * Validate and throw on error (for convenience)
   */
  static parse<T>(schema: SchemaBuilder<T> | Schema, value: unknown): T {
    const result = this.validate(schema, value);

    if (!result.success) {
      throw new ValidationException(result.errors || []);
    }

    return value as T;
  }

  /**
   * Safe parse that returns result object
   */
  static safeParse<T>(
    schema: SchemaBuilder<T> | Schema,
    value: unknown,
  ):
    | { success: true; data: T }
    | { success: false; errors: ValidationError[] } {
    const result = this.validate(schema, value);

    if (result.success) {
      return { success: true, data: value as T };
    } else {
      return { success: false, errors: result.errors || [] };
    }
  }
}

/**
 * Validation exception for parse() method
 */
export class ValidationException extends Error {
  constructor(public errors: ValidationError[]) {
    super(
      "Validation failed:\n" +
        errors.map((e) => `  - ${e.path.join(".")}: ${e.message}`).join("\n"),
    );
    this.name = "ValidationException";
  }
}

/**
 * Auto-initialization wrapper
 * Automatically initializes WASM on first use
 */
export async function createValidator(): Promise<typeof Validator> {
  await initWasm();
  return Validator;
}
